default: &default
  adapter: mysql2
  username: root
  password: 
  host: localhost


development:
  <<: *default
  database: safetynotice_dev

  #host: us-cdbr-iron-east-03.cleardb.net
  #database: heroku_6f99e1591d4f1a3
  #username: b06e19137c0322
  #password: c5f2be4c
test:
  <<: *default
  database: safetynotice_test

production:
  <<: *default
  database: safetynotice_prod

  host: us-cdbr-iron-east-03.cleardb.net
  database: heroku_6f99e1591d4f1a3
  username: b06e19137c0322
  password: c5f2be4c

  # mysql -h us-cdbr-iron-east-03.cleardb.net -u b06e19137c0322 -p heroku_6f99e1591d4f1a3

  # mysql2://b06e19137c0322:c5f2be4c@us-cdbr-iron-east-03.cleardb.net/heroku_6f99e1591d4f1a3?reconnect=true
